### ISSUE TITLE
Localization support for our model fields and help text.

### ISSUE THREAD

**Issue by enderv** [CAWSCIT/ca-meeting-finder-issue-tracker#12]
Copied from: https://github.com/CAWSCIT/caws-api/issues/94
Our model field name (verbose name) and help text should be translatable. 

**Tasks**
- [ ] Determine which languages we need to support 
- [ ] Add help_text to each field (so we only need to translate _once_)
- [ ] Create .po files for proper translations
